name: Build PlatformIO Project

on:
  push:
    branches: [ main, feature-1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: |
          ~/.platformio
        key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-platformio-

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build Sender Environment
      run: |
        pio run -e sender

    - name: Build Receiver Environment
      run: |
        pio run -e receiver

    - name: Check Build Artifacts
      run: |
        echo "Build completed successfully!"
        echo "Sender firmware size:"
        ls -la .pio/build/sender/firmware.bin
        echo "Receiver firmware size:"
        ls -la .pio/build/receiver/firmware.bin
