name: Build and Deploy Web Flasher

on:
  push:
    branches: [main]
    paths:
      - 'web-flasher/**'
      - '!SESSION_NOTES.md'
      - '!README.md'
      - '!docs/**'
      - '!*.md'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'web-flasher/package-lock.json'

      - name: Install dependencies
        run: |
          cd web-flasher
          npm ci

      - name: Build web flasher
        run: |
          cd web-flasher
          npm run build

      - name: Upload Web Flasher Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-flasher-dist
          path: web-flasher/dist/
          retention-days: 30

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Web flasher built successfully! Files are available as artifacts.'
            })
