name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature-1, tests ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
        key: ${{ runner.os }}-platformio-test-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-platformio-test-

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run Comprehensive Unit Tests
      run: |
        chmod +x run_tests.sh
        ./run_tests.sh

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          .pio/build/native/
          test_output.log
        retention-days: 5

  build:
    runs-on: ubuntu-latest
    needs: test

    strategy:
      matrix:
        environment: [sender, receiver]

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
        key: ${{ runner.os }}-platformio-build-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-platformio-build-

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Install Dependencies
      run: |
        pio lib install "jgromes/RadioLib@^6.5.0"
        pio lib install "olikraus/U8g2@^2.36.0"

    - name: Build ${{ matrix.environment }}
      run: |
        pio run -e ${{ matrix.environment }}

    - name: Check Build Output
      run: |
        echo "Build completed for ${{ matrix.environment }}"
        ls -la .pio/build/${{ matrix.environment }}/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ matrix.environment }}
        path: .pio/build/${{ matrix.environment }}/firmware.bin

  lint:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO Check
      run: |
        pio check -e sender-check
        pio check -e receiver-check
